<?php

namespace EPI\InscriptionBundle\Repository;

/**
 * CondidatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CondidatureRepository extends \Doctrine\ORM\EntityRepository
{
}
