<?php

namespace EPI\InscriptionBundle\Repository;

/**
 * imageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class imageRepository extends \Doctrine\ORM\EntityRepository
{
}
