<?php

namespace EPI\InscriptionBundle\Repository;

/**
 * jobSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class jobSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
